

show databases;


CREATE DATABASE VIDEO_DB;

USE VIDEO_DB;

DROP TABLE USERS;

CREATE TABLE USERS 
(
`ID` INT PRIMARY KEY AUTO_INCREMENT,
`LOGIN_NAME` VARCHAR(64) UNIQUE KEY,
`PWD` TEXT
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO USERS(LOGIN_NAME, PWD) VALUES('wangbojing', 'e12ba37ed81660d5c918a919622f78c3');

select * from USERS;

DROP TABLE VIDEO_INFO;

CREATE TABLE VIDEO_INFO 
(
`ID` VARCHAR(64) PRIMARY KEY NOT NULL,
`AUTHOR_ID` INT,
`NAME` TEXT,
`DISPLAY_CTIME` TEXT,
`CREATE_TIME` DATETIME
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM VIDEO_INFO;

INSERT INTO VIDEO_INFO(ID, AUTHOR_ID, NAME, DISPLAY_CTIME) VALUES(?, ?, ?, ?);

SELECT AUTHOR_ID, NAME, DISPLAY_CTIME FROM VIDEO_INFO WHERE AUTHOR_ID= ?;

DELETE FROM VIDEO_INFO WHERE ID='' AND NAME='';

DROP TABLE COMMENTS;

CREATE TABLE COMMENTS
(
`ID` VARCHAR(64) PRIMARY KEY NOT NULL,
`VIDEO_ID` VARCHAR(64) NOT NULL,
`AUTHOR_ID` INT,
`CONTENT` TEXT,
`TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

//02894ee6-a92b-b5fa-d814-6bc6669207da aid 1 content 你好

INSERT INTO COMMENTS(ID, VIDEO_ID, AUTHOR_ID, CONTENT) 
VALUES('02894ee6-a92b-b5fa-d814-6bc6669207da', ?, ?, ?) 


ALTER DATABASE VIDEO_DB CHARACTER SET utf8 COLLATE utf8_unicode_ci; 

 DEFAULT NOW();
drop table COMMENTS;

INSERT INTO COMMENTS(ID, VIDEO_ID, AUTHOR_ID, CONTENT) VALUES(?, ?, ?, ?);

SELECT COMMENTS.ID, USERS.LOGIN_NAME, COMMENTS.CONTENT FROM COMMENTS
INNER JOIN USERS ON COMMENTS.AUTHOR_ID = USERS.ID
WHERE COMMENTS.VIDEO_ID='02894ee6-a92b-b5fa-d814-6bc6669207da' AND COMMENTS.TIME > FROM_UNIXTIME(1514764800) 
AND COMMENTS.TIME <= NOW();

02894ee6-a92b-b5fa-d814-6bc6669207da from 0 to 1538287398949

SELECT COMMENTS.ID, USERS.LOGIN_NAME, 
	COMMENTS.CONTENT FROM COMMENTS 
	INNER JOIN USERS ON COMMENTS.AUTHOR_ID = USERS.ID
	WHERE COMMENTS.VIDEO_ID='02894ee6-a92b-b5fa-d814-6bc6669207da' AND COMMENTS.TIME > FROM_UNIXTIME(0) 
	AND COMMENTS.TIME <= NOW()

select NOW();

select FROM_UNIXTIME(1538287398949);

select * from COMMENTS;

SELECT * FROM VIDEO_INFO;

CREATE TABLE SESSIONS
(
`SESSION_ID` VARCHAR(128) PRIMARY KEY NOT NULL,
`TTL` TINYTEXT,
`LOGIN_NAME` VARCHAR(64)
);

DROP TABLE SESSIONS;

INSERT INTO SESSIONS(SESSION_ID, TTL, LOGIN_NAME) VALUES(?, ?, ?);

DELETE FROM SESSIONS WHERE SESSION_ID=?;

SELECT TTL, LOGIN_NAME FROM SESSIONS WHERE SESSION_ID=?;

CREATE TABLE VIDEO_DEL_REC
(
VIDEO_ID VARCHAR(64) PRIMARY KEY
)

SELECT * FROM VIDEO_DEL_REC

DESC VIDEO_DEL_REC

truncate USERS





